"""
Django settings for GP project.

Generated by 'django-admin startproject' using Django 1.11.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'wq9wojys2&^=@z+bay^n9dnd=j)07d%v8(ulu24s&q2)%dr_*+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['10.13.73.15','.arteliagroup.com']


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'carto.apps.CartoConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'GP.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'carto.context_processors.NotifContext',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'GP.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

"""
DATABASES = {
    'default': { #Cette abse gère uniquement les utilisateurs et les bases de données auxquelles ils ont accès ainsi que les noms des BdD consultables
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'djangoproject4',
        'USER': 'vadjango',
        'PASSWORD': 'admin',
        'HOST': 'localhost',
        'PORT': '',
        'OPTIONS': {
            'options': '-c search_path=public'
        },
    },

    'projet': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'djangoproject4',
        'USER': 'vadjango',
        'PASSWORD': 'admin',
        'HOST': 'localhost',
        'PORT': '',
        'OPTIONS': {
            'options': '-c search_path=projet'
        },
    },

    'import': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'djangoproject4',
        'USER': 'vadjango',
        'PASSWORD': 'admin',
        'HOST': 'localhost',
        'PORT': '',
        'OPTIONS': {
            'options': '-c search_path=importpatrice'
        },
    }
}
"""

DATABASES = {
    'default': { #Cette abse gère uniquement les utilisateurs et les bases de données auxquelles ils ont accès ainsi que les noms des BdD consultables
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'portailgp',
        'USER': 'vadjango',
        'PASSWORD': 'danderas697282',
        'HOST': 'localhost',
        'PORT': '',
        'OPTIONS': {
            'options': '-c search_path=public'
        },
    },

    'projet': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'portailgp',
        'USER': 'vadjango',
        'PASSWORD': 'danderas697282',
        'HOST': 'localhost',
        'PORT': '',
        'OPTIONS': {
            'options': '-c search_path=projet'
        },
    },

}

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
