# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 09:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carto', '0002_auto_20171004_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='password',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='id_user',
            field=models.ForeignKey(db_column='id', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
