# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 09:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carto', '0003_auto_20171004_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='datecreation',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='datederniereconnexion',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='email',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='username',
        ),
    ]
