# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carto', '0005_auto_20171004_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataressource',
            name='datedestruction',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='datasysteme',
            name='datedestruction',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='desordre',
            name='datedestruction',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='environnement',
            name='datedestruction',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='datedestruction',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='etudestrategie',
            name='datedestruction',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='datedestruction',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='gestionnaire',
            name='datedestruction',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='infralineaire',
            name='datedestruction',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='modele',
            name='datedestruction',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='noeud',
            name='datedestruction',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='datedestruction',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='datedestruction',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='datedestruction',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='topo',
            name='datedestruction',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='travaux',
            name='datedestruction',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='zonegeo',
            name='datedestruction',
            field=models.DateField(blank=True),
        ),
    ]
