# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carto', '0006_auto_20171004_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='libelle',
            field=models.IntegerField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='dataressource',
            name='libelle',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='dataressource',
            name='source',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='datasysteme',
            name='libelle',
            field=models.IntegerField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='desordre',
            name='libelle',
            field=models.IntegerField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='environnement',
            name='libelle',
            field=models.IntegerField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='libelle',
            field=models.IntegerField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='etudestrategie',
            name='libelle',
            field=models.IntegerField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='libelle',
            field=models.IntegerField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='gestionnaire',
            name='libelle',
            field=models.IntegerField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='infralineaire',
            name='libelle',
            field=models.IntegerField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='modele',
            name='libelle',
            field=models.IntegerField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='noeud',
            name='libelle',
            field=models.IntegerField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='observation',
            name='libelle',
            field=models.IntegerField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='photo',
            name='libelle',
            field=models.IntegerField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='libelle',
            field=models.IntegerField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='topo',
            name='libelle',
            field=models.IntegerField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='travaux',
            name='libelle',
            field=models.IntegerField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='zonegeo',
            name='libelle',
            field=models.IntegerField(blank=True, max_length=255),
        ),
    ]
