# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 10:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carto', '0010_remove_rapport_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layer',
            name='id',
        ),
        migrations.AddField(
            model_name='layer',
            name='commentaire',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='layer',
            name='datecreation',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='layer',
            name='datedestruction',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='id_layer',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='layer',
            name='libelle',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
