# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 07:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carto', '0011_auto_20171005_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagetiers',
            name='question_text',
        ),
    ]
