# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carto', '0016_auto_20171010_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='localisation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
