# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carto', '0020_objet_lk_zonegeo'),
    ]

    operations = [
        migrations.AddField(
            model_name='objet',
            name='lk_Gestionnaire',
            field=models.ManyToManyField(null=True, through='carto.Tcobjetgestionnaire', to='carto.Gestionnaire'),
        ),
    ]
