# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carto', '0021_objet_lk_gestionnaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='objet',
            name='lk_Ressource',
            field=models.ManyToManyField(null=True, through='carto.Tcobjetressource', to='carto.Ressource'),
        ),
    ]
