# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carto', '0022_objet_lk_ressource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objet',
            name='lk_Gestionnaire',
            field=models.ManyToManyField(blank=True, through='carto.Tcobjetgestionnaire', to='carto.Gestionnaire'),
        ),
        migrations.AlterField(
            model_name='objet',
            name='lk_Ressource',
            field=models.ManyToManyField(blank=True, through='carto.Tcobjetressource', to='carto.Ressource'),
        ),
        migrations.AlterField(
            model_name='objet',
            name='lk_ZoneGeo',
            field=models.ManyToManyField(blank=True, through='carto.Tcobjetzonegeo', to='carto.Zonegeo'),
        ),
    ]
