# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carto', '0023_auto_20171017_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='desordre',
            name='lk_DescriptionSystem',
            field=models.ManyToManyField(blank=True, through='carto.Tcdesordredescriptionsystem', to='carto.Descriptionsystem'),
        ),
        migrations.AddField(
            model_name='etudestrategie',
            name='lk_Travaux',
            field=models.ManyToManyField(blank=True, through='carto.Tcetudetravaux', to='carto.Travaux'),
        ),
        migrations.AddField(
            model_name='travaux',
            name='lk_DescriptionSystem',
            field=models.ManyToManyField(blank=True, through='carto.Tctravauxdescriptionsystem', to='carto.Descriptionsystem'),
        ),
    ]
