# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carto', '0025_auto_20171019_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noeud',
            name='commentaire',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='noeud',
            name='libelle',
            field=models.CharField(max_length=255),
        ),
    ]
