# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carto', '0026_auto_20171019_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='ressource',
            name='lk_objet',
            field=models.ManyToManyField(blank=True, through='carto.Tcobjetressource', to='carto.Objet'),
        ),
    ]
