# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carto', '0027_ressource_lk_objet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataressource',
            name='file',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
