# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carto', '0029_auto_20171019_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='descriptionsystem',
            name='lk_Desordre',
            field=models.ManyToManyField(blank=True, through='carto.Tcdesordredescriptionsystem', to='carto.Desordre'),
        ),
        migrations.AddField(
            model_name='descriptionsystem',
            name='lk_Travaux',
            field=models.ManyToManyField(blank=True, through='carto.Tctravauxdescriptionsystem', to='carto.Travaux'),
        ),
        migrations.AddField(
            model_name='travaux',
            name='lk_Etude',
            field=models.ManyToManyField(blank=True, through='carto.Tcetudetravaux', to='carto.Etudestrategie'),
        ),
    ]
