# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carto', '0030_auto_20171019_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestionnaire',
            name='lk_Objet',
            field=models.ManyToManyField(blank=True, related_name='gestionnaire_associe', through='carto.Tcobjetgestionnaire', to='carto.Objet'),
        ),
        migrations.AddField(
            model_name='zonegeo',
            name='lk_objet',
            field=models.ManyToManyField(blank=True, related_name='emprise', through='carto.Tcobjetzonegeo', to='carto.Objet'),
        ),
        migrations.AlterField(
            model_name='objet',
            name='lk_Gestionnaire',
            field=models.ManyToManyField(blank=True, related_name='gestionnaire_associe', through='carto.Tcobjetgestionnaire', to='carto.Gestionnaire'),
        ),
        migrations.AlterField(
            model_name='objet',
            name='lk_Ressource',
            field=models.ManyToManyField(blank=True, related_name='ressources_associees', through='carto.Tcobjetressource', to='carto.Ressource'),
        ),
        migrations.AlterField(
            model_name='objet',
            name='lk_ZoneGeo',
            field=models.ManyToManyField(blank=True, related_name='emprise', through='carto.Tcobjetzonegeo', to='carto.Zonegeo'),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='lk_objet',
            field=models.ManyToManyField(blank=True, related_name='ressources_associees', through='carto.Tcobjetressource', to='carto.Objet'),
        ),
    ]
