# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 10:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carto', '0031_auto_20171019_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bdd',
            name='id_objet',
            field=models.ForeignKey(db_column='id_objet', on_delete=django.db.models.deletion.CASCADE, to='carto.Objet'),
        ),
        migrations.AlterField(
            model_name='bdd',
            name='id_ressource',
            field=models.ForeignKey(db_column='id_ressource', on_delete=django.db.models.deletion.CASCADE, to='carto.Ressource'),
        ),
        migrations.AlterField(
            model_name='data',
            name='commentaire',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='data',
            name='libelle',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='desordre',
            name='id_objet',
            field=models.ForeignKey(db_column='id_objet', on_delete=django.db.models.deletion.CASCADE, to='carto.Objet'),
        ),
        migrations.AlterField(
            model_name='desordre',
            name='lk_evenement',
            field=models.ForeignKey(blank=True, db_column='id_evenement', null=True, on_delete=django.db.models.deletion.CASCADE, to='carto.Evenement'),
        ),
        migrations.AlterField(
            model_name='environnement',
            name='id_descriptionsystem',
            field=models.ForeignKey(db_column='id_descriptionsystem', on_delete=django.db.models.deletion.CASCADE, to='carto.Descriptionsystem'),
        ),
        migrations.AlterField(
            model_name='environnement',
            name='id_objet',
            field=models.ForeignKey(db_column='id_objet', on_delete=django.db.models.deletion.CASCADE, to='carto.Objet'),
        ),
        migrations.AlterField(
            model_name='environnement',
            name='lk_lineaire',
            field=models.ForeignKey(blank=True, db_column='id_lineaire', null=True, on_delete=django.db.models.deletion.CASCADE, to='carto.Infralineaire'),
        ),
        migrations.AlterField(
            model_name='environnement',
            name='lk_noeud',
            field=models.ForeignKey(blank=True, db_column='id_noeud', null=True, on_delete=django.db.models.deletion.CASCADE, to='carto.Noeud'),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='id_descriptionsystem',
            field=models.ForeignKey(db_column='id_descriptionsystem', on_delete=django.db.models.deletion.CASCADE, to='carto.Descriptionsystem'),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='id_objet',
            field=models.ForeignKey(db_column='id_objet', on_delete=django.db.models.deletion.CASCADE, to='carto.Objet'),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='lk_lineaire',
            field=models.ForeignKey(blank=True, db_column='id_lineaire', null=True, on_delete=django.db.models.deletion.CASCADE, to='carto.Infralineaire'),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='lk_noeud',
            field=models.ForeignKey(blank=True, db_column='id_noeud', null=True, on_delete=django.db.models.deletion.CASCADE, to='carto.Noeud'),
        ),
        migrations.AlterField(
            model_name='etudestrategie',
            name='id_objet',
            field=models.ForeignKey(db_column='id_objet', on_delete=django.db.models.deletion.CASCADE, to='carto.Objet'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='id_objet',
            field=models.ForeignKey(db_column='id_objet', on_delete=django.db.models.deletion.CASCADE, to='carto.Objet'),
        ),
        migrations.AlterField(
            model_name='gestionnaire',
            name='id_objet',
            field=models.ForeignKey(db_column='id_objet', on_delete=django.db.models.deletion.CASCADE, to='carto.Objet'),
        ),
        migrations.AlterField(
            model_name='infralineaire',
            name='id_descriptionsystem',
            field=models.ForeignKey(db_column='id_descriptionsystem', on_delete=django.db.models.deletion.CASCADE, to='carto.Descriptionsystem'),
        ),
        migrations.AlterField(
            model_name='infralineaire',
            name='id_objet',
            field=models.ForeignKey(db_column='id_objet', on_delete=django.db.models.deletion.CASCADE, to='carto.Objet'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='id_objet',
            field=models.ForeignKey(db_column='id_objet', on_delete=django.db.models.deletion.CASCADE, to='carto.Objet'),
        ),
        migrations.AlterField(
            model_name='messagetiers',
            name='id_objet',
            field=models.ForeignKey(db_column='id_objet', on_delete=django.db.models.deletion.CASCADE, to='carto.Objet'),
        ),
        migrations.AlterField(
            model_name='modele',
            name='id_objet',
            field=models.ForeignKey(db_column='id_objet', on_delete=django.db.models.deletion.CASCADE, to='carto.Objet'),
        ),
        migrations.AlterField(
            model_name='modele',
            name='id_ressource',
            field=models.ForeignKey(db_column='id_ressource', on_delete=django.db.models.deletion.CASCADE, to='carto.Ressource'),
        ),
        migrations.AlterField(
            model_name='noeud',
            name='id_descriptionsystem',
            field=models.ForeignKey(db_column='id_descriptionsystem', on_delete=django.db.models.deletion.CASCADE, to='carto.Descriptionsystem'),
        ),
        migrations.AlterField(
            model_name='noeud',
            name='id_objet',
            field=models.ForeignKey(db_column='id_objet', on_delete=django.db.models.deletion.CASCADE, to='carto.Objet'),
        ),
        migrations.AlterField(
            model_name='objet',
            name='lk_projet',
            field=models.ForeignKey(db_column='id_projet', on_delete=django.db.models.deletion.CASCADE, to='carto.Projet'),
        ),
        migrations.AlterField(
            model_name='objet',
            name='lk_utilisateur',
            field=models.ForeignKey(db_column='id_utilisateur', on_delete=django.db.models.deletion.CASCADE, to='carto.Utilisateur'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='id_objet',
            field=models.ForeignKey(db_column='id_objet', on_delete=django.db.models.deletion.CASCADE, to='carto.Objet'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='lk_desordre',
            field=models.ForeignKey(blank=True, db_column='id_desordre', null=True, on_delete=django.db.models.deletion.CASCADE, to='carto.Desordre'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='id_objet',
            field=models.ForeignKey(db_column='id_objet', on_delete=django.db.models.deletion.CASCADE, to='carto.Objet'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='id_ressource',
            field=models.ForeignKey(db_column='id_ressource', on_delete=django.db.models.deletion.CASCADE, to='carto.Ressource'),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='id_objet',
            field=models.ForeignKey(db_column='id_objet', on_delete=django.db.models.deletion.CASCADE, to='carto.Objet'),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='id_ressource',
            field=models.ForeignKey(db_column='id_ressource', on_delete=django.db.models.deletion.CASCADE, to='carto.Ressource'),
        ),
        migrations.AlterField(
            model_name='tcdesordredescriptionsystem',
            name='id_tcdescriptionsystem',
            field=models.ForeignKey(db_column='id_descriptionsystem', on_delete=django.db.models.deletion.CASCADE, to='carto.Descriptionsystem'),
        ),
        migrations.AlterField(
            model_name='tcdesordredescriptionsystem',
            name='id_tcdesordre',
            field=models.ForeignKey(db_column='id_desordre', on_delete=django.db.models.deletion.CASCADE, to='carto.Desordre'),
        ),
        migrations.AlterField(
            model_name='tcetudetravaux',
            name='id_etudestrategie',
            field=models.ForeignKey(db_column='id_etudestrategie', on_delete=django.db.models.deletion.CASCADE, to='carto.Etudestrategie'),
        ),
        migrations.AlterField(
            model_name='tcetudetravaux',
            name='id_travaux',
            field=models.ForeignKey(db_column='id_travaux', on_delete=django.db.models.deletion.CASCADE, to='carto.Travaux'),
        ),
        migrations.AlterField(
            model_name='tcobjetgestionnaire',
            name='id_tcgestionnaire',
            field=models.ForeignKey(db_column='id_gestionnaire', on_delete=django.db.models.deletion.CASCADE, to='carto.Gestionnaire'),
        ),
        migrations.AlterField(
            model_name='tcobjetgestionnaire',
            name='id_tcoobjet',
            field=models.ForeignKey(db_column='id_oobjet', on_delete=django.db.models.deletion.CASCADE, to='carto.Objet'),
        ),
        migrations.AlterField(
            model_name='tcobjetressource',
            name='id_tcoobjet',
            field=models.ForeignKey(db_column='id_oobjet', on_delete=django.db.models.deletion.CASCADE, to='carto.Objet'),
        ),
        migrations.AlterField(
            model_name='tcobjetressource',
            name='id_tcressource',
            field=models.ForeignKey(db_column='id_ressource', on_delete=django.db.models.deletion.CASCADE, to='carto.Ressource'),
        ),
        migrations.AlterField(
            model_name='tcobjetzonegeo',
            name='id_objet',
            field=models.ForeignKey(db_column='id_objet', on_delete=django.db.models.deletion.CASCADE, to='carto.Objet'),
        ),
        migrations.AlterField(
            model_name='tcobjetzonegeo',
            name='id_zonegeo',
            field=models.ForeignKey(db_column='id_zonegeo', on_delete=django.db.models.deletion.CASCADE, to='carto.Zonegeo'),
        ),
        migrations.AlterField(
            model_name='tctravauxdescriptionsystem',
            name='id_tcdescriptionsystem',
            field=models.ForeignKey(db_column='id_descriptionsystem', on_delete=django.db.models.deletion.CASCADE, to='carto.Descriptionsystem'),
        ),
        migrations.AlterField(
            model_name='tctravauxdescriptionsystem',
            name='id_tctravaux',
            field=models.ForeignKey(db_column='id_travaux', on_delete=django.db.models.deletion.CASCADE, to='carto.Travaux'),
        ),
        migrations.AlterField(
            model_name='topo',
            name='id_descriptionsystem',
            field=models.ForeignKey(db_column='id_descriptionsystem', on_delete=django.db.models.deletion.CASCADE, to='carto.Descriptionsystem'),
        ),
        migrations.AlterField(
            model_name='topo',
            name='id_objet',
            field=models.ForeignKey(db_column='id_objet', on_delete=django.db.models.deletion.CASCADE, to='carto.Objet'),
        ),
        migrations.AlterField(
            model_name='travaux',
            name='id_objet',
            field=models.ForeignKey(db_column='id_objet', on_delete=django.db.models.deletion.CASCADE, to='carto.Objet'),
        ),
        migrations.AlterField(
            model_name='travaux',
            name='lk_observation',
            field=models.ForeignKey(db_column='id_observation', on_delete=django.db.models.deletion.CASCADE, to='carto.Observation'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='id_user',
            field=models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='lk_projet',
            field=models.ForeignKey(db_column='id_projet', on_delete=django.db.models.deletion.CASCADE, to='carto.Projet'),
        ),
        migrations.AlterField(
            model_name='video',
            name='id_objet',
            field=models.ForeignKey(db_column='id_objet', on_delete=django.db.models.deletion.CASCADE, to='carto.Objet'),
        ),
        migrations.AlterField(
            model_name='video',
            name='id_ressource',
            field=models.ForeignKey(db_column='id_ressource', on_delete=django.db.models.deletion.CASCADE, to='carto.Ressource'),
        ),
        migrations.AlterField(
            model_name='zonegeo',
            name='id_objet',
            field=models.ForeignKey(db_column='id_objet', on_delete=django.db.models.deletion.CASCADE, to='carto.Objet'),
        ),
    ]
