# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 10:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carto', '0033_auto_20171106_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rapport',
            old_name='rapport',
            new_name='file',
        ),
    ]
