# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 10:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carto', '0034_auto_20171106_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervenant',
            fields=[
                ('datecreation', models.DateField()),
                ('datedestruction', models.DateField(blank=True)),
                ('commentaire', models.CharField(blank=True, max_length=255)),
                ('libelle', models.CharField(max_length=255)),
                ('id_intervenant', models.AutoField(primary_key=True, serialize=False)),
                ('societe', models.CharField(blank=True, max_length=255, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('fax', models.CharField(blank=True, max_length=255, null=True)),
                ('tel', models.CharField(blank=True, max_length=255, null=True)),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'intervenant',
            },
        ),
        migrations.CreateModel(
            name='Tcobjetintervenant',
            fields=[
                ('id_tcobjetintervenant', models.AutoField(primary_key=True, serialize=False)),
                ('gestionnaireouproprietaireouprestataire', models.IntegerField()),
                ('id_tcintervenant', models.ForeignKey(db_column='id_intervenant', on_delete=django.db.models.deletion.CASCADE, to='carto.Intervenant')),
            ],
            options={
                'db_table': 'tcobjetintervenant',
            },
        ),
        migrations.RemoveField(
            model_name='gestionnaire',
            name='id_objet',
        ),
        migrations.RemoveField(
            model_name='gestionnaire',
            name='lk_Objet',
        ),
        migrations.RemoveField(
            model_name='tcobjetgestionnaire',
            name='id_tcgestionnaire',
        ),
        migrations.RemoveField(
            model_name='tcobjetgestionnaire',
            name='id_tcoobjet',
        ),
        migrations.RemoveField(
            model_name='objet',
            name='lk_Gestionnaire',
        ),
        migrations.DeleteModel(
            name='Gestionnaire',
        ),
        migrations.DeleteModel(
            name='Tcobjetgestionnaire',
        ),
        migrations.AddField(
            model_name='tcobjetintervenant',
            name='id_tcoobjet',
            field=models.ForeignKey(db_column='id_oobjet', on_delete=django.db.models.deletion.CASCADE, to='carto.Objet'),
        ),
        migrations.AddField(
            model_name='intervenant',
            name='id_objet',
            field=models.ForeignKey(db_column='id_objet', on_delete=django.db.models.deletion.CASCADE, to='carto.Objet'),
        ),
        migrations.AddField(
            model_name='intervenant',
            name='lk_Objet',
            field=models.ManyToManyField(blank=True, related_name='intervenant_associe', through='carto.Tcobjetintervenant', to='carto.Objet'),
        ),
        migrations.AddField(
            model_name='objet',
            name='lk_Intervenant',
            field=models.ManyToManyField(blank=True, related_name='intervenant_associe', through='carto.Tcobjetintervenant', to='carto.Intervenant'),
        ),
    ]
