# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carto', '0035_auto_20171106_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='nomDB',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
