# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 15:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carto', '0036_projet_nomdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tcobjetzonegeo',
            old_name='id_objet',
            new_name='id_tcobjet',
        ),
        migrations.RenameField(
            model_name='tcobjetzonegeo',
            old_name='id_zonegeo',
            new_name='id_tczonegeo',
        ),
        migrations.RemoveField(
            model_name='objet',
            name='lk_projet',
        ),
        migrations.RemoveField(
            model_name='objet',
            name='lk_utilisateur',
        ),
    ]
