# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carto', '0037_auto_20171109_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcobjetintervenant',
            name='gestionnaireouproprietaireouprestataire',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
