# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 15:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carto', '0040_auto_20171109_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topo',
            name='id_descriptionsystem',
        ),
        migrations.RemoveField(
            model_name='topo',
            name='id_objet',
        ),
        migrations.DeleteModel(
            name='Topo',
        ),
    ]
