# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carto', '0041_auto_20171109_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marche',
            fields=[
                ('id_marche', models.AutoField(primary_key=True, serialize=False)),
                ('datecreation', models.DateField()),
                ('datedestruction', models.DateField(blank=True)),
                ('commentaire', models.CharField(blank=True, max_length=255)),
                ('libelle', models.CharField(max_length=255)),
                ('id_objet', models.ForeignKey(db_column='id_objet', on_delete=django.db.models.deletion.CASCADE, to='carto.Objet')),
            ],
            options={
                'db_table': 'marche',
            },
        ),
        migrations.AddField(
            model_name='pointtopo',
            name='id_objet',
            field=models.ForeignKey(db_column='id_objet', default=-1, on_delete=django.db.models.deletion.CASCADE, to='carto.Objet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topographie',
            name='id_objet',
            field=models.ForeignKey(db_column='id_objet', default=-1, on_delete=django.db.models.deletion.CASCADE, to='carto.Objet'),
            preserve_default=False,
        ),
    ]
