# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carto', '0042_auto_20171109_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudestrategie',
            name='lk_marche',
            field=models.ForeignKey(db_column='id_marche', default=-1, on_delete=django.db.models.deletion.CASCADE, to='carto.Marche'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travaux',
            name='lk_marche',
            field=models.ForeignKey(db_column='id_marche', default=-1, on_delete=django.db.models.deletion.CASCADE, to='carto.Marche'),
            preserve_default=False,
        ),
    ]
