# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 16:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carto', '0043_auto_20171109_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudestrategie',
            name='lk_marche',
        ),
        migrations.RemoveField(
            model_name='travaux',
            name='lk_marche',
        ),
    ]
