# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 08:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carto', '0047_auto_20171110_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desordre',
            name='lk_evenement',
            field=models.ForeignKey(blank=True, db_column='lk_evenement', null=True, on_delete=django.db.models.deletion.CASCADE, to='carto.Evenement'),
        ),
        migrations.AlterField(
            model_name='environnement',
            name='lk_lineaire',
            field=models.ForeignKey(blank=True, db_column='lk_lineaire', null=True, on_delete=django.db.models.deletion.CASCADE, to='carto.Infralineaire'),
        ),
        migrations.AlterField(
            model_name='environnement',
            name='lk_noeud',
            field=models.ForeignKey(blank=True, db_column='lk_noeud', null=True, on_delete=django.db.models.deletion.CASCADE, to='carto.Noeud'),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='lk_lineaire',
            field=models.ForeignKey(blank=True, db_column='lk_lineaire', null=True, on_delete=django.db.models.deletion.CASCADE, to='carto.Infralineaire'),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='lk_noeud',
            field=models.ForeignKey(blank=True, db_column='lk_noeud', null=True, on_delete=django.db.models.deletion.CASCADE, to='carto.Noeud'),
        ),
        migrations.AlterField(
            model_name='etudestrategie',
            name='lk_marche',
            field=models.ForeignKey(blank=True, db_column='lk_marche', null=True, on_delete=django.db.models.deletion.CASCADE, to='carto.Marche'),
        ),
        migrations.AlterField(
            model_name='infralineaire',
            name='lk_noeud1',
            field=models.ForeignKey(blank=True, db_column='lk_noeud1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lk_noeud1', to='carto.Noeud'),
        ),
        migrations.AlterField(
            model_name='infralineaire',
            name='lk_noeud2',
            field=models.ForeignKey(blank=True, db_column='lk_noeud2', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lk_noeud2', to='carto.Noeud'),
        ),
        migrations.AlterField(
            model_name='modele',
            name='lk_marche',
            field=models.ForeignKey(blank=True, db_column='lk_marche', null=True, on_delete=django.db.models.deletion.CASCADE, to='carto.Marche'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='lk_desordre',
            field=models.ForeignKey(blank=True, db_column='lk_desordre', null=True, on_delete=django.db.models.deletion.CASCADE, to='carto.Desordre'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='lk_marche',
            field=models.ForeignKey(blank=True, db_column='lk_marche', null=True, on_delete=django.db.models.deletion.CASCADE, to='carto.Marche'),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='lk_marche',
            field=models.ForeignKey(blank=True, db_column='lk_marche', null=True, on_delete=django.db.models.deletion.CASCADE, to='carto.Marche'),
        ),
        migrations.AlterField(
            model_name='travaux',
            name='lk_marche',
            field=models.ForeignKey(blank=True, db_column='lk_marche', null=True, on_delete=django.db.models.deletion.CASCADE, to='carto.Marche'),
        ),
        migrations.AlterField(
            model_name='travaux',
            name='lk_observation',
            field=models.ForeignKey(db_column='lk_observation', on_delete=django.db.models.deletion.CASCADE, to='carto.Observation'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='lk_projet',
            field=models.ForeignKey(db_column='lk_projet', on_delete=django.db.models.deletion.CASCADE, to='carto.Projet'),
        ),
    ]
