# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 08:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carto', '0048_auto_20171110_0910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pointtopo',
            old_name='Topogragphie',
            new_name='id_topogragphie',
        ),
        migrations.AlterField(
            model_name='bdd',
            name='lk_marche',
            field=models.ForeignKey(blank=True, db_column='lk_marche', null=True, on_delete=django.db.models.deletion.CASCADE, to='carto.Marche'),
        ),
        migrations.AlterField(
            model_name='topographie',
            name='lk_marche',
            field=models.ForeignKey(blank=True, db_column='lk_marche', null=True, on_delete=django.db.models.deletion.CASCADE, to='carto.Marche'),
        ),
    ]
