# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 08:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carto', '0052_auto_20171110_0912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tcobjetintervenant',
            old_name='id_tcoobjet',
            new_name='id_tcobjet',
        ),
        migrations.RenameField(
            model_name='tcobjetressource',
            old_name='id_tcoobjet',
            new_name='id_tcobjet',
        ),
    ]
