# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 08:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carto', '0053_auto_20171110_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rasters',
            fields=[
                ('id_rasters', models.AutoField(primary_key=True, serialize=False)),
                ('datecreation', models.DateField()),
                ('datedestruction', models.DateField(blank=True)),
                ('commentaire', models.CharField(blank=True, max_length=255)),
                ('libelle', models.CharField(max_length=255)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('contactadresse', models.CharField(blank=True, max_length=255, null=True)),
                ('contactnom', models.CharField(blank=True, max_length=255, null=True)),
                ('contactmail', models.CharField(blank=True, max_length=255, null=True)),
                ('contacttel1', models.CharField(blank=True, max_length=255, null=True)),
                ('contacttel2', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('geometry', models.BinaryField()),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('id_objet', models.ForeignKey(db_column='id_objet', on_delete=django.db.models.deletion.CASCADE, to='carto.Objet')),
                ('id_ressource', models.ForeignKey(db_column='id_ressource', on_delete=django.db.models.deletion.CASCADE, to='carto.Ressource')),
                ('lk_marche', models.ForeignKey(blank=True, db_column='lk_marche', null=True, on_delete=django.db.models.deletion.CASCADE, to='carto.Marche')),
            ],
            options={
                'db_table': 'rasters',
            },
        ),
    ]
