# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carto', '0054_rasters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='environnement',
            name='noeudoulineaire',
        ),
        migrations.RemoveField(
            model_name='equipement',
            name='noeudoulineaire',
        ),
        migrations.AddField(
            model_name='equipement',
            name='categorie',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='equipement',
            name='cote',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='equipement',
            name='dimhori',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='equipement',
            name='dimverti',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='equipement',
            name='ecoulement',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='equipement',
            name='implantation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='equipement',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='equipement',
            name='securite',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='equipement',
            name='type_equipement',
            field=models.CharField(blank=True, db_column='type', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='equipement',
            name='utilisation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
