# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carto', '0055_auto_20171110_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterventionTiers',
            fields=[
                ('id_interventionTiers', models.AutoField(primary_key=True, serialize=False)),
                ('datecreation', models.DateField()),
                ('datedestruction', models.DateField(blank=True)),
                ('commentaire', models.CharField(blank=True, max_length=255)),
                ('libelle', models.CharField(max_length=255)),
                ('urgence', models.CharField(blank=True, max_length=255, null=True)),
                ('duree', models.CharField(blank=True, max_length=255, null=True)),
                ('couts', models.DecimalField(blank=True, decimal_places=500, max_digits=999, null=True)),
                ('effectues', models.BooleanField()),
                ('encours', models.BooleanField()),
                ('programme', models.BooleanField()),
                ('echeance', models.DateField(blank=True, null=True)),
                ('datedebut', models.DateField(blank=True, null=True)),
                ('datefin', models.DateField(blank=True, null=True)),
                ('id_objet', models.ForeignKey(db_column='id_objet', on_delete=django.db.models.deletion.CASCADE, to='carto.Objet')),
            ],
            options={
                'db_table': 'interventionTiers',
            },
        ),
        migrations.RemoveField(
            model_name='travaux',
            name='travauxouinterventiontiers',
        ),
    ]
