# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carto', '0056_auto_20171110_1029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interventiontiers',
            old_name='couts',
            new_name='estimationcouts',
        ),
        migrations.RenameField(
            model_name='interventiontiers',
            old_name='duree',
            new_name='estimationduree',
        ),
        migrations.RenameField(
            model_name='interventiontiers',
            old_name='echeance',
            new_name='estimationecheance',
        ),
        migrations.RenameField(
            model_name='travaux',
            old_name='couts',
            new_name='estimationcouts',
        ),
        migrations.RenameField(
            model_name='travaux',
            old_name='duree',
            new_name='estimationduree',
        ),
        migrations.RenameField(
            model_name='travaux',
            old_name='echeance',
            new_name='estimationecheance',
        ),
        migrations.RemoveField(
            model_name='interventiontiers',
            name='effectues',
        ),
        migrations.RemoveField(
            model_name='interventiontiers',
            name='encours',
        ),
        migrations.RemoveField(
            model_name='interventiontiers',
            name='programme',
        ),
        migrations.RemoveField(
            model_name='travaux',
            name='effectues',
        ),
        migrations.RemoveField(
            model_name='travaux',
            name='encours',
        ),
        migrations.RemoveField(
            model_name='travaux',
            name='programme',
        ),
        migrations.AddField(
            model_name='interventiontiers',
            name='phase',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='travaux',
            name='phase',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
