# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carto', '0057_auto_20171110_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rapport',
            name='nom',
        ),
        migrations.AlterField(
            model_name='rapport',
            name='geometry',
            field=models.BinaryField(blank=True),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='source',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
