# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carto', '0058_auto_20171110_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desordre',
            name='lk_evenement',
        ),
        migrations.AddField(
            model_name='desordre',
            name='catdes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='desordre',
            name='cote',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='desordre',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='desordre',
            name='typedes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='desordre',
            name='gravite',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='desordre',
            name='priorite',
            field=models.IntegerField(blank=True),
        ),
    ]
