# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 10:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carto', '0060_auto_20171110_1117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='dataressource',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='datasysteme',
            options={'managed': False},
        ),
        migrations.AlterField(
            model_name='bdd',
            name='datecreation',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='desordre',
            name='datecreation',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='environnement',
            name='datecreation',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='datecreation',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='etudestrategie',
            name='datecreation',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='datecreation',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='infralineaire',
            name='datecreation',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='intervenant',
            name='datecreation',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='interventiontiers',
            name='datecreation',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='marche',
            name='datecreation',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='modele',
            name='datecreation',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='noeud',
            name='datecreation',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='observation',
            name='datecreation',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='photo',
            name='datecreation',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='projet',
            name='datecreation',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='datecreation',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='rasters',
            name='datecreation',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='topographie',
            name='datecreation',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='travaux',
            name='datecreation',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='zonegeo',
            name='datecreation',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
