# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carto', '0061_auto_20171110_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='store',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='desordre',
            name='geometry',
            field=models.BinaryField(db_column='geom'),
        ),
        migrations.AlterField(
            model_name='environnement',
            name='geometry',
            field=models.BinaryField(db_column='geom'),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='geometry',
            field=models.BinaryField(db_column='geom'),
        ),
        migrations.AlterField(
            model_name='infralineaire',
            name='geometry',
            field=models.BinaryField(db_column='geom'),
        ),
        migrations.AlterField(
            model_name='modele',
            name='geometry',
            field=models.BinaryField(db_column='geom'),
        ),
        migrations.AlterField(
            model_name='noeud',
            name='geometry',
            field=models.BinaryField(db_column='geom'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='geometry',
            field=models.BinaryField(db_column='geom'),
        ),
        migrations.AlterField(
            model_name='rasters',
            name='geometry',
            field=models.BinaryField(db_column='geom'),
        ),
        migrations.AlterField(
            model_name='topographie',
            name='geometry',
            field=models.BinaryField(db_column='geom'),
        ),
        migrations.AlterField(
            model_name='zonegeo',
            name='geometry',
            field=models.BinaryField(db_column='geom'),
        ),
    ]
