# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carto', '0062_auto_20171123_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapport',
            name='geometry',
            field=models.BinaryField(blank=True, db_column='geom'),
        ),
        migrations.AlterModelTable(
            name='descriptionsystem',
            table='descriptionsystem_django',
        ),
        migrations.AlterModelTable(
            name='desordre',
            table='desordre_django',
        ),
        migrations.AlterModelTable(
            name='environnement',
            table='environnement_django',
        ),
        migrations.AlterModelTable(
            name='equipement',
            table='equipement_django',
        ),
        migrations.AlterModelTable(
            name='etudestrategie',
            table='etudestrategie_django',
        ),
        migrations.AlterModelTable(
            name='infralineaire',
            table='infralineaire_django',
        ),
        migrations.AlterModelTable(
            name='intervenant',
            table='intervenant_django',
        ),
        migrations.AlterModelTable(
            name='interventiontiers',
            table='interventiontiers_django',
        ),
        migrations.AlterModelTable(
            name='marche',
            table='marche_django',
        ),
        migrations.AlterModelTable(
            name='modele',
            table='modele_django',
        ),
        migrations.AlterModelTable(
            name='noeud',
            table='noeud_django',
        ),
        migrations.AlterModelTable(
            name='objet',
            table='objet_django',
        ),
        migrations.AlterModelTable(
            name='observation',
            table='observation_django',
        ),
        migrations.AlterModelTable(
            name='photo',
            table='photo_django',
        ),
        migrations.AlterModelTable(
            name='rasters',
            table='rasters_django',
        ),
        migrations.AlterModelTable(
            name='ressource',
            table='ressource_django',
        ),
        migrations.AlterModelTable(
            name='topographie',
            table='topographie_django',
        ),
        migrations.AlterModelTable(
            name='travaux',
            table='travaux_django',
        ),
        migrations.AlterModelTable(
            name='zonegeo',
            table='zonegeo_django',
        ),
    ]
